import Head from "next/head";
import { Open_Sans } from "next/font/google";
import CustomTimeline from "../components/CustomTimeline";

const openSans = Open_Sans({
  weights: [400, 600],
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>DashFuel Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${openSans.className}`}>
        <CustomTimeline />
      </main>
    </>
  );
}
